dist: xenial
language: python
cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

jobs:
  allow_failures:
  - python: "3.5"
  - python: "pypy3"

before_install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"

install:
  - "python setup.py install"

script:
  - export SOURCE_FILES="kiss_headers tests"
  - black --check --diff --target-version=py36 $SOURCE_FILES
  - mypy kiss_headers
  - isort --check --diff --project=kiss_headers $SOURCE_FILES
  - pytest

after_success:
  - codecov