language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

jobs:
  allow_failures:
  - python: "3.9-dev"  # See https://github.com/python/mypy/issues/8627

install:
  - pip install pytest pytest-cov codecov isort black requests mypy
  - python setup.py install

script:
  - "black --check --diff --target-version=py36 kiss_headers/"
  - "black --check --diff --target-version=py36 tests/"
  - "mypy kiss_headers"
  - "isort --check-only kiss_headers/*.py"
  - "pytest"

after_success:
  - codecov