language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install nose codecov
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=kiss_headers tests/*.py"

after_success:
  - codecov