language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install nose codecov black requests httpx mypy
  - python setup.py install

script:
  - "black --check --diff --target-version=py36 kiss_headers/"
  - "black --check --diff --target-version=py36 tests/"
  - "mypy kiss_headers"
  - "nosetests --with-coverage --cover-package=kiss_headers tests/*.py"

after_success:
  - codecov