dist: xenial
language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

jobs:
  allow_failures:
  - python: "3.9-dev"  # See https://github.com/python/mypy/issues/8627

install:
  - "./scripts/install"

script:
  - "./scripts/check"

after_success:
  - codecov