site_name: Kiss-Headers
site_description: A stupidly simple way to handle headers from HTTP or IMAP !
site_url: https://kiss-headers.tech/

theme:
    name: 'material'
    logo:
      icon: 'local_florist'
    palette:
      primary: 'teal'
      accent: 'deep orange'

repo_name: ousret/kiss-headers
repo_url: https://github.com/Ousret/kiss-headers/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Basic Usage: 'quickstart.md'
    - Headers: 'advanced-headers.md'
    - Header: 'advanced-header.md'
    - Email: 'imap.md'
    - Contributing: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite
