site_name: Kiss-Headers
site_description: A stupidly simple way to handle headers, object oriented, HTTP or IMAP !
site_url: https://kiss-headers.tech/

theme:
    name: 'material'
    logo:
      icon: 'local_florist'
    palette:
      primary: 'teal'
      accent: 'deep orange'

repo_name: ousret/kiss-headers
repo_url: https://github.com/Ousret/kiss-headers/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Basic Usage: 'quickstart.md'
    - The Theory: 'the-theory.md'
    - Headers: 'advanced-headers.md'
    - Header: 'advanced-header.md'
    - The Builder: 'the-builder.md'
    - Explain Headers: 'explain-headers.md'
    - Email: 'imap.md'
    - API: 'api.md'
    - Contributing: 'contributing.md'

markdown_extensions:
    - toc:
        toc_depth: 3
        permalink: True
    - extra
    - smarty
    - codehilite
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - ../kiss_headers
